In [6]:
import calendar
jul = calendar.month(2025,7,12)
print(jul)

                                        July 2025
   Monday      Tuesday     Wednesday     Thursday      Friday      Saturday      Sunday
                   1            2            3            4            5            6
      7            8            9           10           11           12           13
     14           15           16           17           18           19           20
     21           22           23           24           25           26           27
     28           29           30           31



In [10]:
calendar.isleap(2028)

True

In [27]:
import math
print(math.sqrt(81))


9.0


In [1]:
import numpy as np

a = np.array([10, 20, 30])
b = np.array([1, 2, 3])

print(a + b)
print(a - b)
print(a * b)
print(a / b)


[11 22 33]
[ 9 18 27]
[10 40 90]
[10. 10. 10.]


In [9]:
import numpy as np
q1 = np.array([([44, 22],
              [12,78])])
q2 = np.array([([13,76],
             [88,100])])
print(q1+q2)
print(q1-q2)

[[[ 57  98]
  [100 178]]]
[[[ 31 -54]
  [-76 -22]]]


In [ ]:
import numpy as np
q1 = np.array([([44, 22],
              [12,78])])
q2 = np.array([([13,76],
             [88,100])])
print(q1+q2)
print(q1-q2)